CREATE TABLE IF NOT EXISTS weather (
    `id`                  INTEGER PRIMARY KEY,
    `created_at`          TIMESTAMP NOT NULL,
    `outdoor_humidity`    REAL NOT NULL,
    `outdoor_temperature` REAL NOT NULL,
    `indoor_humidity`     REAL NOT NULL,
    `indoor_temperature`  REAL NOT NULL,
    `solar_irradiance`    REAL NOT NULL,
    `solar_uvi`           REAL NOT NULL,
    `rainfall_daily`      REAL NOT NULL,
    `rainfall_event`      REAL NOT NULL,
    `rainfall_hourly`     REAL NOT NULL,
    `rainfall_monthly`    REAL NOT NULL,
    `rainfall_rate`       REAL NOT NULL,
    `rainfall_state`      REAL NOT NULL,
    `rainfall_weekly`     REAL NOT NULL,
    `rainfall_yearly`     REAL NOT NULL,
    `wind_direction`      REAL NOT NULL,
    `wind_gust`           REAL NOT NULL,
    `wind_speed`          REAL NOT NULL,
    `wind_max_daily_gust` REAL NOT NULL,
    `pressure_absolute`   REAL NOT NULL,
    `pressure_relative`   REAL NOT NULL,
    `battery_voltage`     REAL NOT NULL,
    `capacitor_voltage`   REAL NOT NULL
);
