/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: request.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "request.pb-c.h"
void request__init(Request *message) {
	static const Request init_value = REQUEST__INIT;
	*message = init_value;
}
size_t request__get_packed_size(const Request *message) {
	assert(message->base.descriptor == &request__descriptor);
	return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t request__pack(const Request *message, uint8_t *out) {
	assert(message->base.descriptor == &request__descriptor);
	return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t request__pack_to_buffer(const Request *message, ProtobufCBuffer *buffer) {
	assert(message->base.descriptor == &request__descriptor);
	return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
Request *request__unpack(ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
	return (Request *)protobuf_c_message_unpack(&request__descriptor, allocator, len, data);
}
void request__free_unpacked(Request *message, ProtobufCAllocator *allocator) {
	if (!message)
		return;
	assert(message->base.descriptor == &request__descriptor);
	protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor request__field_descriptors[8] = {
    {
        "session_id", 1, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT64, 0, /* quantifier_offset */
        offsetof(Request, session_id), NULL, NULL, 0,                      /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "ppid", 2, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Request, ppid), NULL, NULL, 0,                      /* flags */
        0, NULL, NULL                                                /* reserved1,reserved2, etc */
    },
    {
        "status_code", 3, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_INT32, 0, /* quantifier_offset */
        offsetof(Request, status_code), NULL, NULL, 0,                     /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "history_id", 4, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT64, 0, /* quantifier_offset */
        offsetof(Request, history_id), NULL, NULL, 0,                      /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "wd", 5, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
        offsetof(Request, wd), NULL, &protobuf_c_empty_string, 0,  /* flags */
        0, NULL, NULL                                              /* reserved1,reserved2, etc */
    },
    {
        "username", 6, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
        offsetof(Request, username), NULL, &protobuf_c_empty_string, 0,  /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "command", 7, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
        offsetof(Request, command), NULL, &protobuf_c_empty_string, 0,  /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "args", 8, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_TYPE_STRING, offsetof(Request, n_args),
        offsetof(Request, args), NULL, &protobuf_c_empty_string, 0, /* flags */
        0, NULL, NULL                                               /* reserved1,reserved2, etc */
    },
};
static const unsigned request__field_indices_by_name[] = {
    7, /* field[7] = args */
    6, /* field[6] = command */
    3, /* field[3] = history_id */
    1, /* field[1] = ppid */
    0, /* field[0] = session_id */
    2, /* field[2] = status_code */
    5, /* field[5] = username */
    4, /* field[4] = wd */
};
static const ProtobufCIntRange request__number_ranges[1 + 1] = {{1, 0}, {0, 8}};
const ProtobufCMessageDescriptor request__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "Request",
    "Request",
    "Request",
    "",
    sizeof(Request),
    8,
    request__field_descriptors,
    request__field_indices_by_name,
    1,
    request__number_ranges,
    (ProtobufCMessageInit)request__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
