"on":
    push:
        branches:
            - master
name: Deploy to 1
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.2.0
            - name: Deploy stack
              timeout-minutes: 30
              run: exec porter apply
              env:
                PORTER_APP_NAME: "1"
                PORTER_CLUSTER: "1"
                PORTER_HOST: https://charlie.withporter.run
                PORTER_PR_NUMBER: ${{ github.event.number }}
                PORTER_PROJECT: "1"
                PORTER_REPO_NAME: ${{ github.event.repository.name }}
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_1_1 }}
